version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar
